/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import user.UserModel;

/**
 *
 * @author mikjakbiak
 */
public class ChooseSubTopicView extends javax.swing.JFrame {
    javax.swing.JFrame previousJFrame;
    UserModel userModel;
    
    /**
     * Creates new form ChooseSubTopicView
     */
    public ChooseSubTopicView() {
        initComponents();
    }

    public ChooseSubTopicView(javax.swing.JFrame previousJFrame, UserModel userModel) {
        this.previousJFrame = previousJFrame;
        this.userModel = userModel;
        initComponents();

        jPanelL1C1.setVisible(false);
        jPanelL1C2.setVisible(false);
        jPanelL2C1.setVisible(false);
        jPanelL2C2.setVisible(false);
        jPanelL3C1.setVisible(false);
        jPanelL3C2.setVisible(false);
        jPanelL4C1.setVisible(false);
        jPanelL4C2.setVisible(false);
        jPanelWIP.setVisible(false);

        switch(userModel.getLanguageLevel()) {
            case 1 -> {
                switch(userModel.getContext()) {
                    case 1 -> {
                        jPanelL1C1.setVisible(true);
                    }
                    case 2 -> {
                        jPanelL1C2.setVisible(true);
                    }
                    default -> {
                        jPanelWIP.setVisible(true);
                    }
                }
            }
            case 2 -> {
                switch(userModel.getContext()) {
                    case 1 -> {
                        jPanelL2C1.setVisible(true);
                    }
                    case 2 -> {
                        jPanelL2C2.setVisible(true);
                    }
                    default -> {
                        jPanelWIP.setVisible(true);
                    }
                }
            }
            case 3 -> {
                switch(userModel.getContext()) {
                    case 1 -> {
                        jPanelL3C1.setVisible(true);
                    }
                    case 2 -> {
                        jPanelL3C2.setVisible(true);
                    }
                    default -> {
                        jPanelWIP.setVisible(true);
                    }
                }
            }
            case 4 -> {
                switch(userModel.getContext()) {
                    case 1 -> {
                        jPanelL4C1.setVisible(true);
                    }
                    case 2 -> {
                        jPanelL4C2.setVisible(true);
                    }
                    default -> {
                        jPanelWIP.setVisible(true);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLayeredPane jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelL1C1 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL1C1S1 = new javax.swing.JButton();
        javax.swing.JButton jButtonL1C1S4 = new javax.swing.JButton();
        javax.swing.JButton jButtonL1C1S3 = new javax.swing.JButton();
        javax.swing.JButton jButtonL1C1S2 = new javax.swing.JButton();
        javax.swing.JButton jButtonL1C1S5 = new javax.swing.JButton();
        jPanelL1C2 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL1C2S6 = new javax.swing.JButton();
        javax.swing.JButton jButtonL1C2S7 = new javax.swing.JButton();
        jPanelL2C1 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL2C1S39 = new javax.swing.JButton();
        javax.swing.JButton jButtonL2C1S40 = new javax.swing.JButton();
        javax.swing.JButton jButtonL2C1S41 = new javax.swing.JButton();
        javax.swing.JButton jButtonL2C1S42 = new javax.swing.JButton();
        javax.swing.JButton jButtonL2C1S43 = new javax.swing.JButton();
        javax.swing.JButton jButtonL2C1S44 = new javax.swing.JButton();
        jPanelL2C2 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL2C2S27 = new javax.swing.JButton();
        jPanelL3C1 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL4C2S61 = new javax.swing.JButton();
        jPanelL3C2 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL3C2S50 = new javax.swing.JButton();
        javax.swing.JButton jButtonL3C2S51 = new javax.swing.JButton();
        javax.swing.JButton jButtonL3C2S52 = new javax.swing.JButton();
        jPanelL4C1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jPanelL4C2 = new javax.swing.JPanel();
        javax.swing.JButton jButtonL3C1S58 = new javax.swing.JButton();
        jPanelWIP = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JButton homeBtn = new javax.swing.JButton();
        javax.swing.JButton backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Linguify_Logo.png"))); // NOI18N

        jLabel2.setText("<html>Choose sub topic");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 182, 182)));

        jButtonL1C1S1.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C1S1.setText("Takeaway");
        jButtonL1C1S1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C1S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C1S1ActionPerformed(evt);
            }
        });

        jButtonL1C1S4.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C1S4.setText("<html>Cocktails by card payment");
        jButtonL1C1S4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C1S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C1S4ActionPerformed(evt);
            }
        });

        jButtonL1C1S3.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C1S3.setText("Reservation");
        jButtonL1C1S3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C1S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C1S3ActionPerformed(evt);
            }
        });

        jButtonL1C1S2.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C1S2.setText("Coffee order");
        jButtonL1C1S2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C1S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C1S2ActionPerformed(evt);
            }
        });

        jButtonL1C1S5.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C1S5.setText("Water for table");
        jButtonL1C1S5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C1S5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C1S5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL1C1Layout = new javax.swing.GroupLayout(jPanelL1C1);
        jPanelL1C1.setLayout(jPanelL1C1Layout);
        jPanelL1C1Layout.setHorizontalGroup(
            jPanelL1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL1C1Layout.createSequentialGroup()
                .addComponent(jButtonL1C1S1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL1C1S4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelL1C1Layout.createSequentialGroup()
                .addComponent(jButtonL1C1S3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL1C1S2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButtonL1C1S5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelL1C1Layout.setVerticalGroup(
            jPanelL1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL1C1Layout.createSequentialGroup()
                .addGroup(jPanelL1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonL1C1S1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL1C1S4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelL1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonL1C1S2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL1C1S3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonL1C1S5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonL1C2S6.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C2S6.setText("Payment");
        jButtonL1C2S6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C2S6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C2S6ActionPerformed(evt);
            }
        });

        jButtonL1C2S7.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL1C2S7.setText("Refund");
        jButtonL1C2S7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL1C2S7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL1C2S7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL1C2Layout = new javax.swing.GroupLayout(jPanelL1C2);
        jPanelL1C2.setLayout(jPanelL1C2Layout);
        jPanelL1C2Layout.setHorizontalGroup(
            jPanelL1C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL1C2Layout.createSequentialGroup()
                .addComponent(jButtonL1C2S6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL1C2S7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelL1C2Layout.setVerticalGroup(
            jPanelL1C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonL1C2S6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonL1C2S7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonL2C1S39.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C1S39.setText("<html>Delayed drinks order");
        jButtonL2C1S39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C1S39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C1S39ActionPerformed(evt);
            }
        });

        jButtonL2C1S40.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C1S40.setText("QR Code");
        jButtonL2C1S40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C1S40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C1S40ActionPerformed(evt);
            }
        });

        jButtonL2C1S41.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C1S41.setText("Cocktails (1)");
        jButtonL2C1S41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C1S41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C1S41ActionPerformed(evt);
            }
        });

        jButtonL2C1S42.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C1S42.setText("Cocktails (2)");
        jButtonL2C1S42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C1S42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C1S42ActionPerformed(evt);
            }
        });

        jButtonL2C1S43.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C1S43.setText("Vegan pizza");
        jButtonL2C1S43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C1S43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C1S43ActionPerformed(evt);
            }
        });

        jButtonL2C1S44.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C1S44.setText("Reservation");
        jButtonL2C1S44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C1S44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C1S44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL2C1Layout = new javax.swing.GroupLayout(jPanelL2C1);
        jPanelL2C1.setLayout(jPanelL2C1Layout);
        jPanelL2C1Layout.setHorizontalGroup(
            jPanelL2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL2C1Layout.createSequentialGroup()
                .addComponent(jButtonL2C1S39, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL2C1S40, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelL2C1Layout.createSequentialGroup()
                .addComponent(jButtonL2C1S41, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL2C1S42, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelL2C1Layout.createSequentialGroup()
                .addComponent(jButtonL2C1S43, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL2C1S44, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelL2C1Layout.setVerticalGroup(
            jPanelL2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL2C1Layout.createSequentialGroup()
                .addGroup(jPanelL2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonL2C1S39, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL2C1S40, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelL2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonL2C1S42, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL2C1S41, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelL2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonL2C1S43, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL2C1S44, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonL2C2S27.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL2C2S27.setText("Payment");
        jButtonL2C2S27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL2C2S27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL2C2S27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL2C2Layout = new javax.swing.GroupLayout(jPanelL2C2);
        jPanelL2C2.setLayout(jPanelL2C2Layout);
        jPanelL2C2Layout.setHorizontalGroup(
            jPanelL2C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL2C2Layout.createSequentialGroup()
                .addComponent(jButtonL2C2S27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanelL2C2Layout.setVerticalGroup(
            jPanelL2C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonL2C2S27, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonL4C2S61.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL4C2S61.setText("Phone purchase");
        jButtonL4C2S61.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL4C2S61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL4C2S61ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL3C1Layout = new javax.swing.GroupLayout(jPanelL3C1);
        jPanelL3C1.setLayout(jPanelL3C1Layout);
        jPanelL3C1Layout.setHorizontalGroup(
            jPanelL3C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL3C1Layout.createSequentialGroup()
                .addComponent(jButtonL4C2S61, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanelL3C1Layout.setVerticalGroup(
            jPanelL3C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonL4C2S61, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonL3C2S50.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL3C2S50.setText("<html>Purchase of computer");
        jButtonL3C2S50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL3C2S50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL3C2S50ActionPerformed(evt);
            }
        });

        jButtonL3C2S51.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL3C2S51.setText("Payment");
        jButtonL3C2S51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL3C2S51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL3C2S51ActionPerformed(evt);
            }
        });

        jButtonL3C2S52.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL3C2S52.setText("<html>Cancel hair appointment");
        jButtonL3C2S52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL3C2S52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL3C2S52ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL3C2Layout = new javax.swing.GroupLayout(jPanelL3C2);
        jPanelL3C2.setLayout(jPanelL3C2Layout);
        jPanelL3C2Layout.setHorizontalGroup(
            jPanelL3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL3C2Layout.createSequentialGroup()
                .addComponent(jButtonL3C2S50, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL3C2S51, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButtonL3C2S52, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelL3C2Layout.setVerticalGroup(
            jPanelL3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL3C2Layout.createSequentialGroup()
                .addGroup(jPanelL3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonL3C2S50, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL3C2S51, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonL3C2S52, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("Nothing here");

        jLabel4.setText("Please choose different topic");

        javax.swing.GroupLayout jPanelL4C1Layout = new javax.swing.GroupLayout(jPanelL4C1);
        jPanelL4C1.setLayout(jPanelL4C1Layout);
        jPanelL4C1Layout.setHorizontalGroup(
            jPanelL4C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL4C1Layout.createSequentialGroup()
                .addGroup(jPanelL4C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelL4C1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3))
                    .addGroup(jPanelL4C1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelL4C1Layout.setVerticalGroup(
            jPanelL4C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL4C1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jButtonL3C1S58.setBackground(new java.awt.Color(255, 224, 214));
        jButtonL3C1S58.setText("<html>Ordering cocktails by barcode");
        jButtonL3C1S58.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButtonL3C1S58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonL3C1S58ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelL4C2Layout = new javax.swing.GroupLayout(jPanelL4C2);
        jPanelL4C2.setLayout(jPanelL4C2Layout);
        jPanelL4C2Layout.setHorizontalGroup(
            jPanelL4C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelL4C2Layout.createSequentialGroup()
                .addComponent(jButtonL3C1S58, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanelL4C2Layout.setVerticalGroup(
            jPanelL4C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonL3C1S58, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel5.setText("Work In Progress");

        jLabel6.setText("Please choose different topic");

        javax.swing.GroupLayout jPanelWIPLayout = new javax.swing.GroupLayout(jPanelWIP);
        jPanelWIP.setLayout(jPanelWIPLayout);
        jPanelWIPLayout.setHorizontalGroup(
            jPanelWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWIPLayout.createSequentialGroup()
                .addGroup(jPanelWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWIPLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5))
                    .addGroup(jPanelWIPLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelWIPLayout.setVerticalGroup(
            jPanelWIPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWIPLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanelL1C1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL1C2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL2C1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL2C2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL3C1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL3C2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL4C1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelL4C2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelWIP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelL1C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL1C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL4C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL4C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelWIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelL1C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL1C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL4C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelL4C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelWIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        homeBtn.setBackground(new java.awt.Color(51, 51, 51));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeNew.png"))); // NOI18N
        homeBtn.setActionCommand("homeBtn");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backNew.png"))); // NOI18N
        backBtn.setActionCommand("backBtn");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void jButtonL1C1S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C1S1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C1S1ActionPerformed

    private void jButtonL1C1S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C1S4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C1S4ActionPerformed

    private void jButtonL1C2S6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C2S6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C2S6ActionPerformed

    private void jButtonL1C2S7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C2S7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C2S7ActionPerformed

    private void jButtonL1C1S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C1S2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C1S2ActionPerformed

    private void jButtonL1C1S5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C1S5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C1S5ActionPerformed

    private void jButtonL1C1S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL1C1S3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL1C1S3ActionPerformed

    private void jButtonL2C1S39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C1S39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C1S39ActionPerformed

    private void jButtonL2C1S40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C1S40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C1S40ActionPerformed

    private void jButtonL2C1S41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C1S41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C1S41ActionPerformed

    private void jButtonL2C1S42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C1S42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C1S42ActionPerformed

    private void jButtonL2C1S43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C1S43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C1S43ActionPerformed

    private void jButtonL2C1S44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C1S44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C1S44ActionPerformed

    private void jButtonL2C2S27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL2C2S27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL2C2S27ActionPerformed

    private void jButtonL4C2S61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL4C2S61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL4C2S61ActionPerformed

    private void jButtonL3C2S50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL3C2S50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL3C2S50ActionPerformed

    private void jButtonL3C2S51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL3C2S51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL3C2S51ActionPerformed

    private void jButtonL3C2S52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL3C2S52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL3C2S52ActionPerformed

    private void jButtonL3C1S58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonL3C1S58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonL3C1S58ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println(previousJFrame);
        // TODO add your handling code here:
        if (previousJFrame != null) {
            this.setVisible(false);
            previousJFrame.setVisible(true);
        }
        
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSubTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSubTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSubTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSubTopicView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseSubTopicView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel jPanelL1C1;
    javax.swing.JPanel jPanelL1C2;
    javax.swing.JPanel jPanelL2C1;
    javax.swing.JPanel jPanelL2C2;
    javax.swing.JPanel jPanelL3C1;
    javax.swing.JPanel jPanelL3C2;
    javax.swing.JPanel jPanelL4C1;
    javax.swing.JPanel jPanelL4C2;
    javax.swing.JPanel jPanelWIP;
    // End of variables declaration//GEN-END:variables
}
